# -*- mode: toml -*-
# vim: set filetype=toml
# atom: set grammar=toml

# General settings and configurations for python project

[tool.pytest.ini_options]
log_level = "INFO"
python_files = "tests_*.py"
testpaths = "tests"

[tool.isort]
extend_skip = ["venv", "env", ".vscode", ".pytest_cache", "mypy_cache"]
include_trailing_comma = true
line_length = 100
multi_line_output = 3
profile = "black"
skip_gitignore = true
supported_extensions = ["py"]

[tool.mypy]
check_untyped_defs = true
disallow_incomplete_defs = true
disallow_untyped_defs = true
files = "src/**/*.py"
ignore_missing_imports = true
no_implicit_optional = true
show_error_codes = true
strict_optional = true
warn_return_any = true
warn_unused_ignores = true

[tool.black]
line_length = 100
exclude = """
/(
  .toml
  |.yaml
  |.sh
  |.git
  |.ini
  |pyproject.toml
  |Dockerfile
  |Pipfile
  |Pipfile.lock
  |env
  |venv
  |build
  |dist
  |.mypy_cache
)/
"""
